name: sleek_spacing
description: Uniformize your margins, paddings and gaps.
version: 0.1.1
homepage: https://github.com/aloisdeniel/sleek_palette

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  provider: ^6.0.0
  freezed_annotation: ^0.14.2
  flutter:
    sdk: flutter

dev_dependencies:
  json_serializable: ^4.1.3
  build_runner: ^2.0.4
  freezed: ^0.14.2
  flutter_test:
    sdk: flutter

flutter:
